# Modified from https://github.com/msys2/setup-msys2/blob/main/examples/cmake.yml
name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '1 2 2/7 * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # - { icon: '🟠', sys: clang32 }
          - { icon: '⚫', sys: mingw32 }
          # - { icon: '🟦', sys: mingw64 }
          # - { icon: '🟨', sys: ucrt64  }
          # - { icon: '🟧', sys: clang64 }
    name: 🚧${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v3

    - name: Cache numdiff
      id: cache-numdiff
      uses: actions/cache@v4
      with:
        path: ${{ runner.workspace }}/${{ matrix.sys }}
        key: ${{ runner.workspace }}-${{ matrix.sys }}

    - name: '${{ matrix.icon }} Setup MSYS2'
      if: steps.cache-numdiff.outputs.cache-hit != 'true'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: >-
          gcc
          make
          texinfo
          texinfo-tex
        # pacboy: >-
        #   texlive-bin:p
        #   texlive-core:p
        #   texlive-plain-generic:p
        #   texlive-fonts-recommended:p
        #   toolchain:p

    - name: 'Test Setup'
      if: steps.cache-numdiff.outputs.cache-hit != 'true'
      run: |
        which gcc
        which make
        which makeinfo
        which texi2pdf
        pacman -Fy
        pacman -F makeinfo
        pacman -F texi2pdf

    - name: '🚧 Build numdiff'
      if: steps.cache-numdiff.outputs.cache-hit != 'true'
      run: |
        mkdir _build
        cd _build
        ../configure --disable-nls --prefix $(cygpath "${{ runner.workspace }}/${{ matrix.sys }}/${{ matrix.sys }}")
        make -j2
        make install
        # cp $(which libgmp-10.dll)  $(cygpath "${{ runner.workspace }}/${{ matrix.sys }}/${{ matrix.sys }}")/bin/.
        # cp $(which libiconv-2.dll) $(cygpath "${{ runner.workspace }}/${{ matrix.sys }}/${{ matrix.sys }}")/bin/.
        # cp $(which libintl-8.dll)  $(cygpath "${{ runner.workspace }}/${{ matrix.sys }}/${{ matrix.sys }}")/bin/.
        ldd $(cygpath "${{ runner.workspace }}/${{ matrix.sys }}/${{ matrix.sys }}")/bin/numdiff.exe
        cp $(which msys-2.0.dll)  $(cygpath "${{ runner.workspace }}/${{ matrix.sys }}/${{ matrix.sys }}")/bin/.
        ldd $(cygpath "${{ runner.workspace }}/${{ matrix.sys }}/${{ matrix.sys }}")/bin/msys-2.0.dll

    - name: 'Upload artifact'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.sys }}-artifact
        path: ${{ runner.workspace }}/${{ matrix.sys }}
